version: "3.9"

services:
  mariadb:
    image: mariadb:11
    restart: always
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: videogames
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: backend
    depends_on:
      - mariadb
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: videogames
    ports:
      - "8081:3000"
    working_dir: /app
    command: npm start

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "1234:80"
    depends_on:
      - backend

volumes:
  mariadb_data:
