version: "3.9"

services:
  mariadb:
    image: mariadb:11
    restart: always
    container_name: videogames-db-dev
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_PORT: 3306
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d